# This workflow will build a Java project with Ant
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-ant

name: Smoke Test Workflow 

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: '8'
        distribution: 'Zulu OpenJDK'
        
    - name: Install ant
      run: wget https://archive.apache.org/dist/ant/binaries/apache-ant-1.9.14-bin.zip
           ant -version
   
