
name: Smoke Test Workflow 

on:
 
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: '8'
        distribution: 'Zulu OpenJDK'
        
    - name: Install ant
      run: wget https://archive.apache.org/dist/ant/binaries/apache-ant-1.9.14-bin.zip
          
    - name: Ant location 
      
      run: java -version 
    - name: java location 
      
      run: whereis java && whereis ant 
    - name: ant location 
      
      run: whereis ant
     
          
      
       
     
